default:
  image: maven:latest
  before_script:
    - mvn clean
    - mvn compile test-compile dependency:build-classpath
    
test:
  stage: test
  script:
    - cd extensions/geojson
    - mvn test
