image: maven:3.6.3-jdk-11

build:
  stage: build
  script: 
    - mvn clean compile test-compile dependency:build-classpath

test:
  stage: test
  script:
    - cd extensions/geojson
    - mvn test dependency:build-classpath
