stages:
  - build
  - test

image: maven:3.6.3-jdk-11

build:
  stage: build
  script: 
    - mvn clean
    - mvn compile test-compile dependency:build-classpath

test:
  stage: test
  needs: [build]
  script:
    - mvn test dependency:build-classpath
